# Generated by Django 4.1.5 on 2023-01-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=50)),
                ('email_content', models.TextField(blank=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('pdf_content', models.TextField(blank=True)),
                ('email_from', models.CharField(max_length=50)),
            ],
        ),
    ]
