# Generated by Django 4.1.5 on 2023-01-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailparser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emails',
            name='email_address',
        ),
    ]
