# Generated by Django 4.1.5 on 2023-01-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailparser', '0002_remove_emails_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='has_pdf',
            field=models.BooleanField(default=False),
        ),
    ]
