# Generated by Django 4.1.5 on 2023-01-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailparser', '0003_emails_has_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='subject',
            field=models.TextField(blank=True),
        ),
    ]
